### PR TITLE
fix: update lambda function to accept json payload

### LINKED ISSUE #42: Lambda Json Payload
Currently, functionless turns a Lambda payload into a array of arguments in the callable `Function`.

```ts
new Function<(arg: string, arg2: string) => string>(...)
```

which actually represent a payload of the form

```ts
{
   arg: string;
   arg2: string;
}
```

This is problematic because 
1. Lambda supports any valid json, including strings and numbers as the payload
2. All integrations with lambda need to use an array of args instead of the more natural object

### Proposal:

Accept any type payload and output to the function as arbitrary json.

```
new Function<{ arg: string, arg2: string }, string>(...); 
```

### PR DESCRIPTION
**Pull request by thantos**
Fixes #42

Previously, Lambda Functions were defined with a type parameter that represented the function signature. Arguments were turned into objects using their names.

```ts
const myFunction = new Function<(arg1: string, arg2: number) => string>(...);

myFunction("some string", 10);

// actual json into the lambda
{
   arg1: "some string:",
   arg2: 10
}
```

This PR updates the function to accept a single Payload argument, matching the public lambda contract that accepts any single JSON input as a parameter.

```ts
const myFunction = new Function<{ arg1: string, arg2: number }, string>(...)

myFunction({ arg1: "some string", arg2: 10 });
```

The payload passed to the lambda function is the same as the above example.

The new representation allows for bare strings, numbers, and nulls.

```ts
const myFunction = new Function<string, string>(...)

myFunction(some string"");
```

This example is passed to the lambda functions as expected, as a bare string.

----

BREAKING CHANGE: Function signature changed from argument list to one or zero arguments for payload as json. Function type parameter is now a payload type and a return type. Function return type defaults to void.

### CODE REVIEW

File: src/function.ts [hunk 1]
```diff
@@ -42,34 +40,32 @@ export type AnyLambda = Function<AnyFunction>;
  *
  * Make sure to implement your Lambda Function entry-points accordingly.
  */
-export class Function<F extends AnyFunction> {
+export class Function<P = undefined, O = void> {
```
Comment (sam-goodwin) [inline src/function.ts:43]: Do we need default types? I think we should encourage the user to specify them. Also the defaults represent a pretty uselsss function haha

File: src/function.ts [hunk 2]
```diff
@@ -42,34 +40,32 @@ export type AnyLambda = Function<AnyFunction>;
...
+  constructor(readonly resource: aws_lambda.IFunction) {
     return Object.assign(lambda, this);
 
     function lambda(call: CallExpr, vtl: VTL): string {
-      const payload = vtl.var(`{}`);
-      for (const [argName, argVal] of Object.entries(call.args)) {
-        vtl.qr(`${payload}.put('${argName}', ${vtl.eval(argVal)})`);
-      }
+      // first argument is the payload
+      const [payloadKey] = Object.keys(call.args);
```
Comment (sam-goodwin) [inline src/function.ts:51]: Could it be undefined?

**Review by sam-goodwin — CHANGES_REQUESTED** [review]

File: src/function.ts (hunk 2 above)
Comment (thantos) [reply src/function.ts:51]: no, because its now the definition of the Function, so I was always getting `args`.

File: src/function.ts (hunk 1 above)
Comment (thantos) [reply src/function.ts:43]: is it useless?

`start()`
`record()`
`increment()`
`submit()`

But sure, we could get rid of the defaults.

Comment (sam-goodwin) [reply src/function.ts:43]: I guess not useless then. Useful for timers and alike. But probably not common?

File: src/function.ts (hunk 2 above)
Comment (sam-goodwin) [reply src/function.ts:51]: What about when P is undefined? Didn't you change the signature to have no args in that case?

Comment (thantos) [reply src/function.ts:51]: it still returns `args` as a property name (the tests seems to work).

Comment (thantos) [reply src/function.ts:51]: Upon more testing, the args map is always returning `args` mapped to either `nullliteral` or a prop accessor, base on 0 or one arguments. Given two arguments it still returns only one.

Putting function brand back and set to the computed `ConditionalFuntion` has returned a more logical result. Will refacto r :+1:

File: src/function.ts (hunk 1 above)
Comment (thantos) [reply src/function.ts:43]: Removed the defaults, always can add it back later.

File: src/function.ts (hunk 2 above)
Comment (sam-goodwin) [reply src/function.ts:51]: Yes function brand is required to give the type of the resolved function to the compiler.

**Review by sam-goodwin — DISMISSED** [review]
When you merge, please make sure the `BREAKING CHANGE:` section is included as the commit message.

**Comment by sam-goodwin** [comment]
Also, can you please update the description to include some examples of how things changed and what customers should do to adapt? Think of the PR description as the content developers will find when their code breaks - it should help them fix it.

**Comment by sam-goodwin** [comment]
Looks like we forgot to update the `README.md`

**Review by sam-goodwin — CHANGES_REQUESTED** [review]
Please make sure to update the README.md with the new syntax.

**Review by sam-goodwin — APPROVED** [review]

**Review by sam-goodwin — APPROVED** [review]
